/**
 * setup-match-onchain.ts — Register match + set player prices/clubs on-chain
 *
 * This script calls the admin transitions to set up a match for the demo:
 *   1. zkfl_match.aleo/register_match
 *   2. zkfl_team_v2.aleo/set_match_clubs
 *   3. zkfl_team_v2.aleo/set_player_price (for each player)
 *   4. zkfl_team_v2.aleo/set_player_club (for each player)
 *   5. zkfl_team_v2.aleo/set_salary_cap
 *   6. zkfl_match.aleo/create_contest
 *
 * Usage: tsx src/setup-match-onchain.ts
 *
 * Reads demo data from data/fixture-demo-fantasy.json (generated by seed-match.ts).
 */

import { readFileSync } from "fs";
import { execSync } from "child_process";
import { config } from "dotenv";

config();

const PRIVATE_KEY = process.env.ALEO_PRIVATE_KEY;
const ENDPOINT = process.env.ALEO_ENDPOINT ?? "https://api.explorer.provable.com/v1";

if (!PRIVATE_KEY) {
  console.error("Missing ALEO_PRIVATE_KEY in .env");
  process.exit(1);
}

const CONTRACTS_DIR = "../contracts";

// Map v2 program names to their directory names (dirs didn't change)
const DIR_MAP: Record<string, string> = {
  zkfl_team_v2: "zkfl_team",
  zkfl_scoring_v2: "zkfl_scoring",
  zkfl_prize_v2: "zkfl_prize",
};

function leo(contractName: string, fn: string, inputs: string[]): string {
  const dirName = DIR_MAP[contractName] ?? contractName;
  const inputStr = inputs.join(" ");
  const cmd = [
    "leo execute",
    fn,
    inputStr,
    "--network testnet",
    `--private-key ${PRIVATE_KEY}`,
    `--endpoint "${ENDPOINT}"`,
    "--broadcast --yes",
  ].join(" ");

  console.log(`  ${contractName}/${fn}(${inputs.slice(0, 3).join(", ")}${inputs.length > 3 ? "..." : ""})`);

  const output = execSync(cmd, {
    cwd: `${CONTRACTS_DIR}/${dirName}`,
    encoding: "utf-8",
    timeout: 120_000,
  });

  const txMatch = output.match(/at1[a-z0-9]+/);
  return txMatch ? txMatch[0] : "unknown";
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

/**
 * CLI usage:
 *   tsx src/setup-match-onchain.ts                    # run all steps
 *   tsx src/setup-match-onchain.ts --step 3           # run only step 3 (set_player_price)
 *   tsx src/setup-match-onchain.ts --step 3 --only 113,112  # step 3 for specific players
 *   tsx src/setup-match-onchain.ts --step 4 --only 113      # step 4 for specific players
 *
 * Steps: 1=register_match, 2=set_match_clubs, 3=set_player_price,
 *        4=set_player_club, 5=set_salary_cap, 6=create_contest
 */
async function main() {
  // Parse CLI args
  const args = process.argv.slice(2);
  const stepIdx = args.indexOf("--step");
  const onlyIdx = args.indexOf("--only");
  const stepFilter = stepIdx !== -1 ? Number(args[stepIdx + 1]) : null;
  const onlyPlayers = onlyIdx !== -1 ? args[onlyIdx + 1].split(",").map(Number) : null;

  // Load demo data
  const data = JSON.parse(readFileSync("data/fixture-demo-fantasy.json", "utf-8"));
  const matchId = data.match_id; // e.g. "1field"
  const homeClubId = data.home_club_id; // 1
  const awayClubId = data.away_club_id; // 2
  const prices: Record<string, number> = data.player_prices;
  const clubs: Record<string, number> = data.player_clubs;

  console.log("═══════════════════════════════════════════════");
  console.log("Setting up match on-chain");
  if (stepFilter) console.log(`  Running step ${stepFilter} only`);
  if (onlyPlayers) console.log(`  Players: ${onlyPlayers.join(", ")}`);
  console.log("═══════════════════════════════════════════════\n");

  const kickoffBlock = "1000000u32";
  // NOTE: The real on-chain contest_id is a BHP256 hash of ContestSeed.
  // After create_contest, use the hash from the tx output.
  // Update contestId below after running step 6 with the new nonce.
  const NONCE = "43field";
  // Contest hash for nonce=43field:
  const contestId = "5622599938287340955314218888251884005964792045382263630126017545486724441981field";

  // 1. Register match
  if (!stepFilter || stepFilter === 1) {
    console.log("1. Registering match...");
    leo("zkfl_match", "register_match", [matchId, `${homeClubId}u32`, `${awayClubId}u32`, kickoffBlock]);
    await sleep(10_000);
  }

  // 2. Set match clubs
  if (!stepFilter || stepFilter === 2) {
    console.log("\n2. Setting match clubs...");
    leo("zkfl_team_v2", "set_match_clubs", [matchId, `${homeClubId}u32`, `${awayClubId}u32`]);
    await sleep(10_000);
  }

  // 3. Set player prices
  if (!stepFilter || stepFilter === 3) {
    console.log("\n3. Setting player prices...");
    // Player 0 is the dummy for unused formation slots — must exist on-chain
    if (!onlyPlayers || onlyPlayers.includes(0)) {
      try {
        leo("zkfl_team_v2", "set_player_price", [matchId, "0u32", "0u128"]);
        await sleep(10_000);
      } catch {
        console.error("    Failed for player 0 (dummy), continuing...");
      }
    }
    for (const [playerId, price] of Object.entries(prices)) {
      if (onlyPlayers && !onlyPlayers.includes(Number(playerId))) continue;
      try {
        leo("zkfl_team_v2", "set_player_price", [matchId, `${playerId}u32`, `${price}u128`]);
        await sleep(10_000);
      } catch {
        console.error(`    Failed for player ${playerId}, continuing...`);
      }
    }
  }

  // 4. Set player clubs
  if (!stepFilter || stepFilter === 4) {
    console.log("\n4. Setting player clubs...");
    // Player 0 dummy — club 0 so it doesn't count as home or away
    if (!onlyPlayers || onlyPlayers.includes(0)) {
      try {
        leo("zkfl_team_v2", "set_player_club", ["0u32", "0u32"]);
        await sleep(10_000);
      } catch {
        console.error("    Failed for player 0 (dummy), continuing...");
      }
    }
    for (const [playerId, clubId] of Object.entries(clubs)) {
      if (onlyPlayers && !onlyPlayers.includes(Number(playerId))) continue;
      try {
        leo("zkfl_team_v2", "set_player_club", [`${playerId}u32`, `${clubId}u32`]);
        await sleep(10_000);
      } catch {
        console.error(`    Failed for player ${playerId}, continuing...`);
      }
    }
  }

  // 5. Set salary cap
  if (!stepFilter || stepFilter === 5) {
    console.log("\n5. Setting salary cap...");
    leo("zkfl_team_v2", "set_salary_cap", [contestId, "100000000u128"]);
    await sleep(10_000);
  }

  // 6. Create contest
  if (!stepFilter || stepFilter === 6) {
    console.log("\n6. Creating contest...");
    leo("zkfl_match", "create_contest", [
      matchId,               // match_id
      "1000000u128",         // entry_fee (1 credit = 1_000_000 microcredits)
      "100u32",              // max_entries
      "602515u32",           // prize_split (60/25/15)
      "1u8",                 // contest_type (classic)
      kickoffBlock,          // deadline_block
      NONCE,                 // nonce
    ]);
  }

  console.log("\n═══════════════════════════════════════════════");
  console.log("Setup complete!");
  console.log("═══════════════════════════════════════════════");
}

main().catch(console.error);
