/**
 * setup-match4-onchain.ts — Register Bayern Munich vs Dortmund on-chain
 *
 * Steps:
 *   1. zkfl_match.aleo/register_match         (match_id = 4field)
 *   2. zkfl_team_v2.aleo/set_match_clubs
 *   3. zkfl_team_v2.aleo/set_player_price × 25
 *   4. zkfl_team_v2.aleo/set_player_club  × 25
 *   5. zkfl_team_v2.aleo/set_salary_cap
 *   6. zkfl_match.aleo/create_contest
 *      → prints contest_id hash → paste into seed-match4.ts (server)
 *
 * Usage:
 *   tsx src/setup-match4-onchain.ts                 # run all steps
 *   tsx src/setup-match4-onchain.ts --step 6        # re-run contest creation only
 *   tsx src/setup-match4-onchain.ts --step 3 --only 710,810   # retry specific players
 *
 * Reads from data/fixture-match4-fantasy.json (generated by seed-match4.ts).
 *
 * WORKFLOW:
 *   1. Run step 6 first to get the contest_id hash
 *   2. Update contestId below with the printed hash
 *   3. Run step 5 to set salary cap with the real contest_id
 *   4. Update server/src/db/seed-match4.ts with the same hash
 */

import { readFileSync } from "fs";
import { execSync } from "child_process";
import { config } from "dotenv";

config();

const PRIVATE_KEY = process.env.ALEO_PRIVATE_KEY;
const ENDPOINT = process.env.ALEO_ENDPOINT ?? "https://api.explorer.provable.com/v1";

if (!PRIVATE_KEY) {
  console.error("Missing ALEO_PRIVATE_KEY in .env");
  process.exit(1);
}

const CONTRACTS_DIR = "../contracts";

const DIR_MAP: Record<string, string> = {
  zkfl_team_v2: "zkfl_team",
  zkfl_scoring_v2: "zkfl_scoring",
  zkfl_prize_v2: "zkfl_prize",
};

function leo(contractName: string, fn: string, inputs: string[]): string {
  const dirName = DIR_MAP[contractName] ?? contractName;
  const inputStr = inputs.join(" ");
  const cmd = [
    "leo execute",
    fn,
    inputStr,
    "--network testnet",
    `--private-key ${PRIVATE_KEY}`,
    `--endpoint "${ENDPOINT}"`,
    "--broadcast --yes",
  ].join(" ");

  console.log(`  ${contractName}/${fn}(${inputs.slice(0, 3).join(", ")}${inputs.length > 3 ? "..." : ""})`);

  const output = execSync(cmd, {
    cwd: `${CONTRACTS_DIR}/${dirName}`,
    encoding: "utf-8",
    timeout: 120_000,
  });

  // Print contest_id field if returned (create_contest output)
  const fieldMatch = output.match(/(\d{30,}field)/);
  if (fieldMatch) {
    console.log("\n  ╔══════════════════════════════════════════════════════╗");
    console.log(`  ║  contest_id hash: ${fieldMatch[1]}`);
    console.log("  ║  → update contestId in this file");
    console.log("  ║  → paste into server/src/db/seed-match4.ts");
    console.log("  ╚══════════════════════════════════════════════════════╝\n");
  }

  const txMatch = output.match(/at1[a-z0-9]+/);
  return txMatch ? txMatch[0] : "unknown";
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

async function main() {
  const args = process.argv.slice(2);
  const stepIdx = args.indexOf("--step");
  const onlyIdx = args.indexOf("--only");
  const stepFilter = stepIdx !== -1 ? Number(args[stepIdx + 1]) : null;
  const onlyPlayers = onlyIdx !== -1 ? args[onlyIdx + 1].split(",").map(Number) : null;

  // Load match4 fixture
  const data = JSON.parse(readFileSync("data/fixture-match4-fantasy.json", "utf-8"));
  const matchId = data.match_id;           // "4field"
  const homeClubId = data.home_club_id;    // 7 (Bayern Munich)
  const awayClubId = data.away_club_id;    // 8 (Dortmund)
  const prices: Record<string, number> = data.player_prices;
  const clubs: Record<string, number> = data.player_clubs;

  const kickoffBlock = "2200000u32";
  const NONCE = "52field";

  // ── UPDATE THIS after running step 6 ──
  // Run: tsx src/setup-match4-onchain.ts --step 6
  // Copy the printed hash and paste it here, then run --step 5
  const contestId = "1field"; // PLACEHOLDER — replace after step 6

  console.log("═══════════════════════════════════════════════");
  console.log("Setting up Match 4 on-chain (Bayern Munich vs Dortmund)");
  console.log(`  Match ID : ${matchId}  Home: ${homeClubId} (BAY)  Away: ${awayClubId} (DOR)`);
  console.log(`  Nonce    : ${NONCE}`);
  if (stepFilter) console.log(`  Running step ${stepFilter} only`);
  if (onlyPlayers) console.log(`  Players  : ${onlyPlayers.join(", ")}`);
  if (contestId === "1field") console.log("  ⚠ contestId is placeholder — run step 6 first, then update and run step 5");
  console.log("═══════════════════════════════════════════════\n");

  // 1. Register match
  if (!stepFilter || stepFilter === 1) {
    console.log("1. Registering match...");
    leo("zkfl_match", "register_match", [matchId, `${homeClubId}u32`, `${awayClubId}u32`, kickoffBlock]);
    await sleep(10_000);
  }

  // 2. Set match clubs
  if (!stepFilter || stepFilter === 2) {
    console.log("\n2. Setting match clubs...");
    leo("zkfl_team_v2", "set_match_clubs", [matchId, `${homeClubId}u32`, `${awayClubId}u32`]);
    await sleep(10_000);
  }

  // 3. Set player prices
  if (!stepFilter || stepFilter === 3) {
    console.log("\n3. Setting player prices...");
    if (!onlyPlayers || onlyPlayers.includes(0)) {
      try {
        leo("zkfl_team_v2", "set_player_price", [matchId, "0u32", "0u128"]);
        await sleep(10_000);
      } catch {
        console.error("    Failed for player 0 (dummy), continuing...");
      }
    }
    for (const [playerId, price] of Object.entries(prices)) {
      if (onlyPlayers && !onlyPlayers.includes(Number(playerId))) continue;
      try {
        leo("zkfl_team_v2", "set_player_price", [matchId, `${playerId}u32`, `${price}u128`]);
        await sleep(10_000);
      } catch {
        console.error(`    Failed for player ${playerId}, continuing...`);
      }
    }
  }

  // 4. Set player clubs
  if (!stepFilter || stepFilter === 4) {
    console.log("\n4. Setting player clubs...");
    if (!onlyPlayers || onlyPlayers.includes(0)) {
      try {
        leo("zkfl_team_v2", "set_player_club", ["0u32", "0u32"]);
        await sleep(10_000);
      } catch {
        console.error("    Failed for player 0 (dummy), continuing...");
      }
    }
    for (const [playerId, clubId] of Object.entries(clubs)) {
      if (onlyPlayers && !onlyPlayers.includes(Number(playerId))) continue;
      try {
        leo("zkfl_team_v2", "set_player_club", [`${playerId}u32`, `${clubId}u32`]);
        await sleep(10_000);
      } catch {
        console.error(`    Failed for player ${playerId}, continuing...`);
      }
    }
  }

  // 5. Set salary cap (run AFTER step 6 with real contestId)
  if (!stepFilter || stepFilter === 5) {
    console.log("\n5. Setting salary cap...");
    if (contestId === "1field") {
      console.error("  ✗ contestId is still placeholder! Run step 6 first, update contestId, then re-run --step 5");
      process.exit(1);
    }
    leo("zkfl_team_v2", "set_salary_cap", [contestId, "100000000u128"]);
    await sleep(10_000);
  }

  // 6. Create contest — prints contest_id hash in output
  if (!stepFilter || stepFilter === 6) {
    console.log("\n6. Creating contest...");
    leo("zkfl_match", "create_contest", [
      matchId,        // 4field
      "1000000u128",  // entry_fee (1 credit)
      "100u32",       // max_entries
      "602515u32",    // prize_split (60/25/15)
      "1u8",          // contest_type (classic)
      kickoffBlock,   // deadline_block
      NONCE,          // 52field
    ]);
    console.log("\n  ▶ Copy the contest_id hash above.");
    console.log("  ▶ Update contestId in this file and re-run --step 5.");
    console.log("  ▶ Open server/src/db/seed-match4.ts and update CONTEST_ON_CHAIN_ID.");
    console.log("  ▶ Then run: cd ../server && npm run seed:match4");
  }

  console.log("\n═══════════════════════════════════════════════");
  console.log("Done!");
  console.log("═══════════════════════════════════════════════");
}

main().catch(console.error);
